### ISSUE TITLE
Use of logo on GitHub Explore

### ISSUE THREAD

**Issue by donovanglover** [latex3/branding#1]
Hello,

I am requesting permission to use the LaTeX logo on [GitHub Explore](https://github.com/github/explore).

The logo you provide should be 288x288. It will show up above the LaTeX name [like this](https://github.com/topics/crystal).

Please let me know if you accept (or reject) this proposal!

**Comment by FrankMittelbach** [comment]
sorry for the late reply. The L3 logos are indented to mark the brand LaTeX Project team brand/work and as such we do not want to see it used in any place where its use might indicate that it is "official work" of the LaTeX3 Project team when in fact it isn't. I need to make that clear on the README of this site.

However, with your use  I don't see no problem whatsoever. If you expect us to provide the logo at a specific size we might need some time to provide that. So if you can't use what is available right now please say so and I will see what is possible during the next days.

**Comment by donovanglover** [comment]
Thanks for your reply. I believe that a version of the hummingbird by itself would look really nice above the LaTeX name. What do you think?

https://github.com/latex3/branding/blob/master/latex-project_logo/material/hummingbird.svg

It would be great if you guys could make a 288x288 .png of this.

**Comment by jonasjacek** [comment]
@GloverDonovan 
I have just uploaded a square version of the official logo:
https://github.com/latex3/branding/blob/master/latex-project_logo/latex-project-logo_288x288.png
https://github.com/latex3/branding/blob/master/latex-project_logo/latex-project-logo_288x288.svg
Feel free to use it for linking to the LaTeX Project in GitHub Explore.

Kind regards, Jonas
